fourth homework
js-tasks-ru/js-20220111_v-svintsov pull request #3
Opened 2022-01-26 20:32 UTC by vasya28

2022-01-26 20:33 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-01-27 12:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-01-27 22:13 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +      isNeedRender = true
зачем необходим данный аргумент?

2022-01-27 22:13 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +  get chartHeight() {
почему данное значение объявлено как геттер а не как обычное свойство класса?

2022-01-27 22:13 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    for (const subElement of this.element.querySelectorAll('[data-element]')) {
было бы неплохо вынести данную логику в отдельный метод

2022-01-27 22:14 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    const scale = 50 / maxValue;
что такое 50? может `chartHeight`?

2022-01-27 22:14 UTC, dosandk requested changes
хорошо, но нужно дать ответы на вопросы

2022-01-29 16:33 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-01-29 20:08 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-01-30 23:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-02-01 15:46 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +const LOCALES = ["ru-RU", "en-US"];
почему данные значения находятся за пределами класса?

2022-02-01 15:47 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    const orderByToCompareFunction = {
в данном объекте. присутствуют дубликаты кода, от них следует избавиться

2022-02-01 15:47 UTC, dosandk approved these changes
good 👍

2022-02-01 15:48 UTC, merged